# Generated by Django 3.0.3 on 2020-03-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazons', '0003_amazons'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazons',
            name='month_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amazons',
            name='month_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amazons',
            name='month_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amazons',
            name='month_4',
            field=models.BooleanField(default=True),
        ),
    ]
