# Generated by Django 3.0.3 on 2020-02-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
